### ISSUE TITLE
Cannot install via Project Installer

### ISSUE THREAD

**Issue by AlexHoebart-ICPDR** [backdrop-contrib/content_lock#3] opened 2024-04-05 12:39 UTC
When trying to install this module via the Backdrop "Install new modules" page (Project Installer), the following error is displayed:

> Error installing Content locking (edit lock). Unable to retrieve Backdrop project from https://github.com/backdrop-contrib/content_lock/releases/download/1.x-2.2/content_lock.zip.

Also on the [Project page](https://backdropcms.org/project/content_lock), the download link points to a wrong URL https://github.com/backdrop-contrib/content_lock/releases/download/1.x-2.2/content_lock.zip.

There is currently only a version 1.x-2.2.1, so I don't know why this happens, just wanted to report it.

**Comment by argiepiano** [comment] 2024-04-10 13:27
I think the issue is that the module record in backdrocms.org is faulty. My guess is that the maintainer first did a release tagged 1.x-2.2, which was picked by b-org, then edited the name to 1.x-2.2.1, but b-org for some reason did not pick that change. My second guess is that because the first tag was missing the patch digit (last digit after the last period), then this created issues for b-org.

If you look at the module on b-org you'll see what I'm talking about:
https://backdropcms.org/project/content_lock

The solution doesn't lie in this module. Someone with access needs to modify the record on b-org. The fastest way to get this done is to ask someone on Backdrop's Zulip channel. I'll do that now.

**Comment by argiepiano** [comment] 2024-04-10 15:00
This has been solved in backdropcms.org. The project can now be installed with Project Installer. Closing this issue.

**Closed as completed by argiepiano** 2024-04-10 15:00 UTC

**Comment by AlexHoebart-ICPDR** [comment] 2024-04-10 15:08
Very good, thank you - will use the shortcut via Zulip channel next time as well when I find a similar issue.
